kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: test-foo
  ownerReferences:
  - apiVersion: samplecontroller.k8s.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Foo
    name: test-foo
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  replicas: 1
status: 
  availableReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1  
---
kind: Pod
apiVersion: v1
metadata:
  namespace: default
  labels:
    app: nginx
    controller: test-foo
spec:
  containers:
    - name: nginx
      image: nginx:latest
status:
  phase: Running
